AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  catdex-serverless
  
  Sample SAM Template for catdex-serverless

Globals:
  Function:
    Timeout: 3

Resources:
  CatTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: cat
        Type: String

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  GetCatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/get-cats/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [ "arm64" ]
      Events:
        GetCats:
          Type: Api
          Properties:
            Path: /cats
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref CatTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CatTable

  PostCatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: >
        catdex-hello-world-api
        
        Sample template, just to test is it working
      CodeUri: target/lambda/post-cat/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: ["arm64"]
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /cat
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref CatTable
          BUCKET_NAME: !Ref ImageBucket
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref CatTable
        - S3WritePolicy:
            BucketName: !Ref ImageBucket

Outputs:
  PostApi:
    Description: "API Gateway endpoint URL for Pord stage for Post function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  GetCatsFunction:
    Description: "Get Cats Lambda Function ARN"
    Value: !GetAtt GetCatsFunction.Arn
  PostCatFunction:
    Description: "Post Lambda Function ARN"
    Value: !GetAtt PostCatFunction.Arn
  CatTable:
    Description: "DynamoDB table name"
    Value: !GetAtt CatTable.Arn
